patch:
  menu/page_size: 6

  ascii_composer/good_old_caps_lock: true
  ascii_composer/switch_key/Caps_Lock: clear
  ascii_composer/switch_key/Shift_L: clear
  ascii_composer/switch_key/Shift_R: clear
  ascii_composer/switch_key/Control_L: noop
  ascii_composer/switch_key/Control_R: noop
