# refer to
# https://github.com/KyleBing/rime-wubi86-jidian/wiki/%E7%9A%AE%E8%82%A4%E9%85%8D%E7%BD%AE%E8%AF%A6%E8%A7%A3
# https://github.com/LEOYoon-Tsaw/Rime_collections/blob/master/%E9%BC%A0%E9%AC%9A%E7%AE%A1%E4%BB%8B%E9%9D%A2%E9%85%8D%E7%BD%AE%E6%8C%87%E5%8D%97.md
# https://zhaohongxuan.github.io/2024/03/20/most-powerful-input-method-rime/#Patch-%E8%87%AA%E5%AE%9A%E4%B9%89%E7%9A%AE%E8%82%A4
# https://gist.github.com/lewangdev/f8ebbba24f464e915fb7d36857fcbbe5
# https://zhuanlan.zhihu.com/p/150716121

patch:
  app_options:
    com.microsoft.VSCode:
      ascii_mode: true
      ascii_punct: true
    com.cursor.Cursor:
      ascii_mode: true
      ascii_punct: true
    com.jetbrains.intellij:
      ascii_mode: true
      ascii_punct: true
    com.googlecode.iterm2:
      ascii_mode: true
      ascii_punct: true
    com.apple.Terminal:
      ascii_mode: true
      ascii_punct: true
    md.obsidian:
      ascii_punct: true

  style/color_scheme: mac
  style/color_scheme_dark: mac_dark
  style/candidate_format: " [label]  [candidate] [comment] \u200a"
  style/label_font_point: 14
  style/font_face: ""
  style/border_height: -3
  style/border_width: -3

  preset_color_schemes:
    mac:
      name: macOS Light
      author: "lonr <https://lonr.eu.org>"
      back_color: 0xf1f2f2 # background
      label_color: 0x808080 # label
      candidate_text_color: 0x494949 # candidate
      comment_text_color: 0x494949 # comment
      hilited_candidate_back_color: 0xd85a00
      hilited_candidate_label_color: 0xffffff
      hilited_candidate_text_color: 0xffffff
      hilited_comment_text_color: 0xffffff
      # text_color: 0x808080                    # 拼音颜色 （inline_preedit: false）
      # hilited_text_color: 0xEEEEEE            # 选中拼音颜色 （inline_preedit: false）
      # candidate_back_color:                 # 候选项底色
      # preedit_back_color:                   # 拼音底色 （inline_preedit: false）
      # hilited_back_color:                   # 选中拼音底色 （inline_preedit: false）
      # border_color:                         # 外边框颜色

    mac_dark:
      name: macOS Dark
      author: "lonr <https://lonr.eu.org>"
      back_color: 0x393939
      label_color: 0x7b7b7b
      candidate_text_color: 0xebebeb
      comment_text_color: 0xebebeb
      hilited_candidate_back_color: 0xd15900
      hilited_candidate_label_color: 0xffffff
      hilited_candidate_text_color: 0xffffff
      hilited_comment_text_color: 0xffffff
