# Rime stays in Chinese mode; use macOS to switch to English.
patch:
  "switches/@0":
    name: ascii_mode
    reset: 0
  "engine/processors":
    - t9_processor
    - recognizer
    - key_binder
    - speller
    - punctuator
    - selector
    - navigator
    - express_editor
